gavin_sharingcode/urls.py
# Module 0
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # new url
    path('', include('share.urls'))

]

share/urls.py
# Module 0
from django.urls import path, include
from . import views  #import everything from views module
app_name = 'share'
urlpatterns = [
    path('signup',views.signup, name='signup'),
    path('create',views.create, name='create'),
    path('login',views.login_view, name='login'),
    path('loguser',views.login_user,name='loguser'),
    path('logout',views.logout_view, name='logout'),
    path('',views.index, name='index'),
    path('dashboard', views.dashboard, name='dashboard'),
    # problems
    path('problem/publish', views.publish_problem, name='publish_problem'),
    path('problem/<int:problem_id>/show', views.show_problem, name='show_problem'),
    path('problem/<int:problem_id>/edit', views.edit_problem,  name='edit_problem'),
    path('problem/<int:problem_id>/update', views.update_problem, name='update_problem'),
    path('problem/<int:problem_id>/delete', views.delete_problem, name='delete_problem'),
    path('problem/create', views.create_problem, name='create_problem'),
    path('problem/<int:problem_id>/build_script', views.build_script, name='build_script'),
    path('problem/<int:problem_id>/create_script', views.create_script, name='create_script'),
    # scripts
    path('script/<int:script_id>/show', views.show_script, name='show_script'),
    path('script/<int:script_id>/edit', views.edit_script, name='edit_script'),
    path('script/<int:script_id>/update', views.update_script, name='update_script'),
    path('script/<int:script_id>/delete', views.delete_script, name='delete_script'),
    path('scripts',views.scripts, name='scripts'),
    # reviews
    path('script/<int:script_id>/create_review', views.create_review, name='create_review'),
    path('review/<int:review_id>/delete_review', views.delete_review, name='delete_review'),
    #search
    path('search', views.search, name='search'),

]

urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

share/models.py
from django.db import models

from django.contrib.auth.models import User

from django.utils import timezone

    # Module 10
from django.core.validators import MaxValueValidator, MinValueValidator

# Module 0
# Script model
class Coder(models.Model):
    def __str__(self):
        return self.user.username

    coder_yet = models.BooleanField(default=False)  # the user is not a coder yet
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    created = models.DateField(auto_now_add=True)   # maybe redundant, user model has date_joined
    updated = models.DateField(auto_now=True)

# Module 1 Step 2  Create Problem model
class Problem(models.Model):
    def __str__(self):
        return self.title

    coder = models.ForeignKey(Coder, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, null=False, blank=False, unique=False)
    description = models.CharField(max_length=100, null=False, blank=False, unique=False)
    image = models.ImageField(upload_to='myproblems/', blank=True)
    discipline = models.CharField(max_length=50, null=False, blank=False, unique=False)
    make_public = models.BooleanField(default=True)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)     # everytime the obj is saved, new time is saved

    def num_of_scripts(self):
	    scripts = Script.objects.filter(problem=self)
	    return len(scripts)

# Module 0 Create Script model
# Module 1 Step 3 Update Script model
class Script(models.Model):
    def __str__(self):
        return self.title
    # FK
    coder = models.ForeignKey(Coder, on_delete=models.CASCADE, null=True)
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE, null=True)

    title = models.CharField(max_length=50, null=False, blank=False, unique=False)
    description = models.TextField(max_length=100, null=False, blank=False, unique=False)
    code = models.TextField(max_length=10000, unique=False)
    url = models.URLField(max_length=300, unique=False, blank=True)

    input = models.TextField(max_length=100, unique=False, blank=True)
    output = models.TextField(max_length=100, unique=False, blank=True)
    make_public = models.BooleanField(default=True)

    image = models.ImageField(upload_to='myscripts/', blank=True)  # add an image for the algorithm or flow chart
    working_code = models.BooleanField(default=True)

    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    def num_of_reviews(self):
	       reviews = Review.objects.filter(script=self)
	       return len(reviews)

    def avg_review(self):
    		sum = 0
    		reviews = Review.objects.filter(script=self)
    		for r in reviews:
    			sum += r.stars

    		if len(reviews) > 0:
    			return sum / len(reviews)
    		else:
    			return 0


class Review(models.Model):
	def __str__(self):
		return self.feedback

	script = models.ForeignKey(Script, on_delete=models.CASCADE)
	coder = models.ForeignKey(Coder, on_delete=models.CASCADE)
	stars = models.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(3)])
	feedback = models.TextField(max_length=200, unique=False, blank=True)

	class Meta:
		unique_together = (('coder', 'script'),)

share/views.py
from django.http import HttpResponse
# Module 3 imports
# import three functions: authentication, login, logout
from django.contrib.auth import authenticate, login, logout
# import redirect
from django.shortcuts import render, redirect, get_object_or_404
# import all the models created so far
from .models import Script, Problem, Coder
# import User model
from django.contrib.auth.models import User
from share.models import Script, Problem, Coder, Review
from share.find_offensive_language import offensive


def signup(request):
    if request.user.is_authenticated:
        return redirect("share:index")
    return render(request, 'share/signup.html')
def create(request):
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        coder_yet = request.POST.get('coder_yet_checkbox' , False)

        if username is not None and email is not None and password is not None: # checking that they are not None
            if not username or not email or not password: # checking that they are not empty
                return render(request, "share/signup.html", {"error": "Please fill in all required fields"})
            if User.objects.filter(username=username).exists():
                return render(request, "share/signup.html", {"error": "Username already exists"})
            elif User.objects.filter(email=email).exists():
                return render(request, "share/signup.html", {"error": "Email already exists"})
            # save our new user in the User model
            user = User.objects.create_user(username, email, password)
            coder = Coder.objects.create(user= user, coder_yet = coder_yet).save()
            user.save()

            login(request, user, backend="django.contrib.auth.backends.ModelBackend")
            # this logs in our new user, backend means that we are using the  Django specific auhentication and not 3rd party

        return redirect("share:index")

    else:
        return redirect("share:signup")
def login_view(request):
    if request.user.is_authenticated:
        return redirect("share:index")
    return render(request, 'share/login.html')
def login_user(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        if not username or not password:
            return render(request, "share/login.html", {"error":"One of the fields was empty"})
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("share:index")
        else:
            return render(request, "share/login.html", {"error":"Wrong username or password"})
    else:
        return redirect("share:index")
def logout_view(request):
    logout(request)
    return redirect("share:login")
def index(request):
    # Testing http request object inside a view function
    print('*********** Testing request obj ************')
    print('request:' , request)
    print('request.headers: ', request.headers)
    print('request.headers["host"]:', request.headers['host'])
    print('request.method: ', request.method)
    print('request.user:' , request.user)
    print('*******************************')

    if request.method == "GET":
        if request.user.is_authenticated:
            user = request.user
            all_problems = Problem.objects.all()   # all_problems is a list object [   ]

            return render(request, "share/index.html", {"user":user, "all_problems": all_problems})
        else:
            return redirect("share:login")
    else:
        return HttpResponse(status=500)
def dashboard(request):
    # retieve user, my_problems, my-scripts
    # builds my_problems_scripts dict
    # renders dashboard.html
    # each problem should have a link show more details of a particular problem,
    # this link starts route show_my_problem

    # Testing http request object inside a view function
    print('*********** Testing request obj ************')
    print('request:' , request)
    print('request.headers: ', request.headers)
    print('request.headers["host"]:', request.headers['host'])
    print('request.method: ', request.method)
    print('request.user:' , request.user)
    print('*******************************')

    if request.method == "GET":
        user = request.user
        if not user.is_authenticated:
            return redirect("share:login")
        else:
            my_problems = Problem.objects.filter(coder=user.coder.id)   # Problem table has a coder field (FK)
            my_scripts =  Script.objects.filter(coder=user.coder.id)

            print('*********** Testing objs retrieved from DB ************')
            print('my_problems:', my_problems)
            print('my_scripts:', my_scripts)
            print('*******************************')

            return render(request, "share/dashboard.html", {"my_scripts": my_scripts, "my_problems": my_problems })
def publish_problem(request):
    if request.method == "GET":
        user = request.user
        if not user.is_authenticated:
            return redirect("share:login")
        else:
            return render(request, "share/publish_problem_form.html", {"user":user} )
def create_problem(request):
    if request.method == "POST":
        user = request.user
        if not user.is_authenticated:
            return redirect("share:login")

        coder = user.coder
        title = request.POST["title"]
        description = request.POST["description"]
        discipline = request.POST["discipline"]
        make_public = request.POST.get('make_public', False)
        if make_public == 'on':
            make_public = True
        else:
            make_public = False

        if not title and not description:
            return render(request, "share/publish_problem_form.html",
             {"error":"Please fill in all required fields"})

        try:
            problem = Problem.objects.create(coder=coder, title=title,
             description=description, discipline=discipline, make_public=make_public)
            problem.save()

            problem = get_object_or_404(Problem, pk=problem.id)
            scripts = Script.objects.filter(problem=problem.id)

            return render(request, "share/problem.html",{"user":user,
             "problem":problem, "scripts": scripts})

        except:
            return render(request, "share/publish_problem_form.html",
             {"error":"Can't create the problem"})

    else:
        # the user enteing    http://127.0.0.1:8000/problem/8/create
        user = request.user
        all_problems = Problem.objects.all()
        return render(request, "share/index.html",
        {"user":user, "all_problems": all_problems, "error":"Can't create!"})
def show_problem(request, problem_id):
    if request.method == "GET":
        user = request.user
        if not user.is_authenticated:
            return redirect("share:login")
            user_script = Script.objects.filter(coder=user.id).filter(problem=problem.id)
        else:
            # make sure to import the fucntion get_object_or_404 from  django.shortcuts
            problem = get_object_or_404(Problem, pk=problem_id)
            scripts = Script.objects.filter(problem=problem_id)

            # Module 6
            if problem.make_public or problem.coder.user.id == user.id:
                return render(request, "share/problem.html",
                {"user":user, "problem":problem, "scripts": scripts})
            else:
                # the problem is private and you are not the author
                return render(request, "share/index.html",
                {"error":"The problem you clicked is still private and you are not the author"})
def edit_problem(request, problem_id):
    if request.method == "GET":
        user = request.user
        if not user.is_authenticated:
            return redirect("share:login")

        problem = get_object_or_404(Problem, pk=problem_id)

        # does this problem have any scripts? if yes you can't update or delete
        scripts = Script.objects.filter(problem=problem_id)

        if problem.coder.user.id == user.id and not scripts and not problem.make_public:
            return render(request, "share/edit_problem.html", {"problem":problem})
        elif not problem.coder.user.id == user.id:
            return render(request, "share/index.html",
            {"error":"You are not the author of the problem that you tried to edit."})
        elif problem.coder.user.id == user.id:
            return render(request, "share/index.html",
            {"error":"You problem has scripts and you cannot edit it."})
def update_problem(request, problem_id):
    if request.method == "POST":
        user = request.user
        if not user.is_authenticated:
            return HttpResponse(status=500)


        problem = get_object_or_404(Problem, pk=problem_id)

        if not request.POST["title"] or not request.POST["description"] or not request.POST["discipline"]:
            return render(request, "share/edit_problem.html", {"problem":problem,
            "error":"One of the required fields was empty"})

        else:
            title = request.POST["title"]
            description = request.POST["description"]
            discipline = request.POST["discipline"]

            make_public = request.POST.get('make_public', False)
            print('***********************')
            print('user input make_public:', make_public)    # it shows as on

            if make_public == 'on':
                make_public = True
            else:
                make_public = False

            print('******** Testing *************')
            print('make_public:', make_public)
            print('***********************')

            if problem.coder.user.id == user.id:

share/templates/share/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Python Thinkers</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'share/bulma-0.8.0/css/bulma.css' %}"/>
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'share/main.css' %}"/>
</head>

<body>
  <nav class="navbar is-primary" role="navigation" aria-label="main navigation">


   <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'share:index' %}">
            <img src="{% static 'share/images/thinking-face.png' %}" alt=" icon" width="40" height="60">
            Python <br>Thinkers
        </a>
        </a class="navbar-item">

      <!--   https://bulma.io/documentation/components/navbar/  for responsive sites-->
      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarData">
       <span aria-hidden="true"></span>
       <span aria-hidden="true"></span>
       <span aria-hidden="true"></span>
     </a>

    </div>

    <div id="navbarData" class="navbar-menu is-active" >
      <!-- navbar-menu hidden in mobile devices -->
      <!-- is-actice makes id show in mobile devices -->
      <div class="navbar-start">

     <a class="navbar-item" href="{% url 'share:dashboard' %}">My Dashboard</a>

    <div class="navbar-item has-dropdown is-hoverable">
       <a class="navbar-link">
         More
       </a>

       <div class="navbar-dropdown">
          <a class="navbar-item" href="{% url 'share:index' %}">All Problems</a>
          <a class="navbar-item" href="{% url 'share:publish_problem' %}">Post a Problem</a>
          <a class="navbar-item" href="{% url 'share:scripts' %}">All Python Scripts</a>


       </div>

     </div>
   </div>

   <div class="navbar-end">
         <div class="navbar-item">
           <div class="buttons">

             {% if request.path == "/login" or request.path == "/loguser" %}
             <a class="button is-primary" href="{% url 'share:signup' %}">Signup</a>

              {% elif request.path == "/signup"  %}

              <a class="button is-primary" href="{% url 'share:login' %}">Login</a>

              {% else   %}
               <div class="navbar-item">
                      <form action="{% url 'share:search' %}" method="post">
                          {% csrf_token %}
                          <p class="control has-icons-left">
                              <input class="input" type="text" name="query" placeholder="search">
                              <span class="icon is-left">
                          <i class="fas fa-search"></i>
                        </span>
                          </p>
                      </form>
                </div>
               <a class="button is-primary" href="{% url 'share:logout' %}">Logout {{user.username }}</a>

             {% endif %}

           </div>
         </div>
       </div>
     </div>
     </nav>

<section class="section">
    <div class="container">
        {% block content %} {% endblock content %}
    </div>
</section>

</body>
</html>

share/templates/share/dashboard.html
<!-- list problems and scripts that belong to this coder -->
{% extends "share/base.html" %}
{% block content %}

    <div class="columns">
        <div class="column">
            <div class="tile is-ancestor has-text-centered">
                <div style="margin: auto;" class="tile is-parent">
                    <div class="tile is-child box">
                        <h1 class="title is-2"> Hello &nbsp<span style="color:#1496ed">{{ user.username }}</span></h1>

                        <h4 class="title is-5">You can publish new problems here:</h4>
                        <a class="button is-info is-medium" href="{% url 'share:publish_problem' %}">Publish a new problem</a>
                    </div>
                </div>
            </div>

                <!-- This is only for testing to see the objects were passed to the template by the view -->
<!--
                <hr> ############ testing #######  <br>
                my_problems: {{my_problems}} <br>
                my_scripts: {{my_scripts}} <br>
                ################################## <br> -->


                <hr>
                    <div class="box">
                    <h2 class="title" style="color:#00d1b2">Problems defined by you:</h2>
                    {% for p in my_problems %}
                            <div class="content"> {{ p.title }}
                              <a class="button is-primary is-small" href="{% url 'share:show_problem' p.id %}">Show more ...</a>
                                                                  <!-- create show_my_problem route right away -->

                            </div>
                    {% endfor %}
                    </div>

                    <div class="box">
                      <h2 class="title " style="color:#00d1b2">Scripts written by you:</h2>
                    {% for s in my_scripts %}
                            <div class="content">
                                <br>Script Title: {{ s.title }}, Solves: {{ s.problem.title }}, posted by {{s.problem.coder.user.username}}

                                <a class="button is-primary is-small" href="{% url 'share:show_script' s.id %}">Show more ...</a>
                                                                  <!-- create show_my_script route right away -->
                            </div>
                    {% endfor %}
                    </div>
        </div>
    </div>

{% endblock content %}

share/templates/share/problem.html
{% extends "share/base.html" %}
{% block content %}

<!-- objects passed by the view function: user, problem, scripts  -->

    <div class="columns">
        <div class="column">

          {% if error %}
            <h3 class="title is-3" style="color: red">{{ error }}</h3>
          {% endif %}

            <h2 class="title is-2">Problem defined by:
              <span style="color:blue">{{ problem.coder.user.username }}</span>
            </h2>
            <div class="box">
              <div class="content">

                  Title: {{ problem.title }} <br><br>
                  Description: {{ problem.description }} <br><br>
                  Discipline: {{ problem.discipline }} <br><br>
                  Created on {{ problem.created }} <br><br>

                  <!-- Module 6 -->
                  {% if problem.make_public %}
                    This problem is public! <br><br>
                  {% else %}
                    This problem is private!<br><br>
                  {% endif %}

                  <!-- Module 6 -->
                  {% if scripts %}  <!-- only show this block if there are solutions to this problem -->
                    <br>Solutions to this problem:
                    <div class="box">
                      {% for s in scripts %}
                        <div class="content">
                            <br>Script title: {{ s.title }}, written by  {{s.coder.user.username}}
                            <a class="button is-primary is-small"
                            href="{% url 'share:show_script' s.id %}">Show the script ...</a>

                        </div>
                      {% endfor %}
                    </div>
                    {% else %}

                    These are NO solutions written for this problem

                  {% endif %}
                  <br><br>
                  {% if user.id == problem.coder.user.id and not scripts and not problem.make_public  %}
                    <a class="button is-primary is-medium"
                       href="{% url 'share:edit_problem' problem.id %}">Make changes to this problem ... </a>
                  {% endif %}

                  <br><br>
                  <!-- Module 9 -->

                  {% if not user_script %}
                  <a class="button is-primary is-medium"
                    href="{% url 'share:build_script' problem.id %}">Create a Python solution for this problem ... </a>
                  {% endif %}   
              </div>
          </div>

        </div>
    </div>

{% endblock content %}

share/templates/share/script.html
{% extends "share/base.html" %}
{% block content %}
<!-- objects passed by the view function: user, script, problem, reviews, user_review -->
{% if error %}
  <h3 class="title is-3" style="color: red">{{ error }}</h3>
{% endif %}

<!--
<hr> ##### testing ####  <br>
problem: {{problem}} <br>
script: {{script}} <br>
reviews: {{reviews}} <br>
user_review: {{ user_review }} <br>
######################## <br>
-->

<div class="columns">
  <div class="column is-three-forths-widescreen" >
    <h2 class="title is-2">Python script: {{ script.title }} <br>Written by {{ script.coder.user.username}}</h2>
        <div class="box">
          <div class="content"><br>
              Description: {{ script.description }} <br>
              {% if script.url %}
                URL: {{ script.url }} <br>
              {% endif %}
              {% if script.input %}
                Input: {{ script.input }} <br>
              {% endif %}
              {% if script.output %}
                Output: {{ script.output }} <br>
              {% endif %}
              {% if script.working_code %}
                This script is working! <br><br>
              {% else %}
                This script is not yet working!<br><br>
              {% endif %}
              Created on {{ script.created }}, Updated on {{ script.updated }} <br><br>
              {% if script.make_public %}
                This script is public! <br><br>
              {% else %}
                This script is private!<br><br>
              {% endif %}
              <!-- create a link to the problem that it solves -->
              Problem that solves:
              <a class="button is-primary is-small" href="{% url 'share:show_problem' problem.id %}">  {{ problem.title}} </a>,
                posted by {{problem.coder.user.username}} <br><br><br>
              <div class="box">     <!-- we should also show the RAW text --> <!-- See pastebin -->
              Python code:
                    <div class="code">
                          <br>{{ script.code }}
                      </div>
              </div><br>
              {% if user.id == script.coder.user.id %}
                <a class="button is-primary is-medium"
                href="{% url 'share:edit_script' script.id %}">Make changes to this script ... </a>
              {% endif %}
              <!-- Module 10 Review form -->
              <!-- if the user has already written a review, show the content of the review on the right column, button to delete -->
              <!-- if the logged user has not written a review yet and
              she is not the author of the script, then show the review form -->
              {% if not user_review and user.id != script.coder.user.id %}
                <h2 class="title is-4">Write your review </h2>
                  <form action="{% url 'share:create_review' script.id %}" method="post">
                      {% csrf_token %}
                      I found this solution to be:
                      <!-- https://versions.bulma.io/0.7.1/documentation/form/radio/  -->
                      <span class="control">
                        <label class="radio"> <input type="radio" value = "confusing" name="stars"> Confusing </label>
                        <label class="radio"> <input type="radio" value = "clear" name="stars"> Clear </label>
                        <label class="radio"> <input type="radio" value = "outstanding" name="stars"> Outstanding </label>
                      </span>
                    <!-- http://versions.bulma.io/0.7.1/documentation/form/textarea/ -->
                    <div class="field"> <div class="control"> <textarea class="textarea is-warning" name="feedback"
                        placeholder="e.g. thank you for writing this solution, I was wondering if ..."></textarea></div>
                    </div>
                    <div class="field">
                      <div class="control"> <button class="button is-success is-outlined" type="submit">
                      Post review </button>&nbsp;
                      </div>
                    </div>
                </form>
              {% endif %}
            </div>
        </div>
  </div> <!-- column -->
<!-- Module 10 This column is to list all the reviews for this script -->
<!-- Add recent reviews on the right column -->
  <div class="column is-one-quarter"><br><br>
    <h2 class="title is-4">Reviews</h2>
            <div class="box">
              <div class="content">
                {% if reviews %}
                  {% for r in reviews %}
                      {% if r.stars == 1 %} Confusing
                      {% elif r.stars == 2 %} Clear
                      {% elif r.stars == 3 %} Outstanding
                      {% endif %}
                      by {{r.coder.user.username}} <br>
                      {{ r.feedback }}<br>
                    {% if r.coder.user.id == user.id %}
                    <form action="{% url 'share:delete_review' r.id %}" method="post">
                        {% csrf_token %}
                         <button class="button is-danger is-outlined" type="submit" name="delete" value="Delete">
                           Delete My Review</button>&nbsp;
                    </form>
                    {% endif %}
              </div>
                  {% endfor %}
                {% else %}
                  No reviews yet!
                {% endif %}
              </div>
        </div>
</div> <!-- columns -->
{% endblock content %}

share/templates/share/search_result.html
{% extends "share/base.html" %}
{% block content %}
<!-- objects passed by the view function: user, scripts, query -->

    {% if error %}
        <h3 style="color: red">{{ error }}</h3>

    {% endif %}
    <div class="columns">
        <div class="column">
            <h1 style="color: #0f81cc" class="title">Search results for {{query}}</h1>
            {% for s in scripts %}
                <div class="box">
                    <div class="content">
                      {% if s.title %}
                      Python script: {{ s.title }} <br>Written by {{ s.coder.user.username}}
                      <a class="button is-primary is-small"
                      href="{% url 'share:show_script' s.id %}">Show the script ...</a>
                      {% endif %}
                      <br>
            {% endfor %}

            {% for p in problems %}
                      {% if p.title %}
                      Pyhton problems: {{ p.title }} <br>Written by {{ p.coder.user.username}}
                      <a class="button is-primary is-small"
                      href="{% url 'share:show_problem' p.id %}">Show the problem ...</a>
                      {% endif %}
                    </div>
                </div>
                <br>
            {% endfor %}

        </div>
    </div>


{% endblock content %}

share/templates/share/show_my_script.html
{% extends "share/base.html" %}

{% block content %}

<h2 class="title is-2">Python script </h2>
        <div class="box">
        <div class="content">
            {% if script.make_public %}

              Title of the python script: {{ my_script.title }} <br>
              Description: {{ my_script.description }} <br>
              Created on {{ my_script.created }} <br>
              Problem that solves: {{ problem.title}}, posted by {{problem.coder.user.username}} <br>
              Script written by: {{ script.coder.user.username}}
              <br>
              <br>
              <div class="box">
              Python script:
                    <div class="code">
                          <br>{{ my_script.code }}
                      </div>
              </div>


                <a class="button is-primary is-medium" href="{% url 'share:edit_script' script.id %}">Make changes to this script </a>


      
            {% endif %}

        </div>
    </div>

{% endblock content %}